import type { AccountProviderDefinition } from "./types";

export const catpawProvider: AccountProviderDefinition = {
  id: "catpaw",
  label: "CatPawAI",
  filterLabel: "CatPawAI",
  exportFilename: "webchat2api_catpaw.txt",
  exportButtonLabel: "导出 CatPaw TXT",
  selectedExportButtonLabel: "导出所选 CatPaw TXT",
  canExportWithoutTokens: false,
  importTokenCopy: {
    label: "暂不支持",
    placeholder: "CatPawAI 请使用扫码登录导入账号。",
    fileHelp: "CatPawAI 不支持 TXT token 导入，请使用扫码登录。",
    successLabel: "CatPaw 扫码登录完成",
    submitLabel: "暂不支持",
  },
  importSessionCopy: {
    label: "暂不支持",
    placeholder: "CatPawAI 请使用扫码登录导入账号。",
    help: "CatPawAI 使用扫码登录，无需手动粘贴凭据。",
    successLabel: "CatPaw 扫码登录完成",
    submitLabel: "暂不支持",
    parseJsonAccessToken: false,
  },
  importMethods: ["qr-login"],
  importFlowCopy: {
    providerDescription: "通过扫码登录导入 CatPawAI（美团 MCopilot）账号，自动获取并续期 token。",
    methodIntro: "CatPawAI 使用扫码登录：点击开始后用大象/微信扫描二维码并确认，系统会自动获取 token 并加入号池，后台自动续期。",
    emptyMethodsLabel: "当前没有可用的 CatPawAI 导入方式。",
    cpaHelp: "当前 CatPawAI 不支持本地 JSON 文件导入。",
    remoteCpaDescription: "当前 CatPawAI 不支持远程 CPA 快捷入口。",
    sub2apiDescription: "当前 CatPawAI 不支持 Sub2API 快捷入口。",
  },
  metadataLabel: "CatPaw 账号 / 登录状态",
  accountInfoHelp: "用于 CatPawAI 聊天号池，扫码登录后自动获取并续期访问令牌。",
  tokenHiddenLabel: "CatPaw token hidden",
  badgeVariant: "outline",
  quota: {
    applicable: true,
    metricLabel: "CatPaw credits",
    unavailableLabel: "未知",
    unlimitedTypes: [],
  },
  refresh: {
    enabled: true,
    buttonLabel: "续期 CatPaw token",
    selectedButtonLabel: "续期选中 CatPaw token",
    rowTitle: "通过 refresh token 续期 CatPaw 访问令牌",
  },
  trial: {
    enabled: true,
    textFallbackModels: ["glm-5", "kimi-k2.6", "deepseek-v3.2"],
    textFallbackMode: "always",
    imageFallbackModels: [],
    imageUnsupportedCopy: "CatPawAI 暂未提供图像生成/编辑接口，请切换到文本试验或选择其他服务。",
    imageNoMetadataCopy: "CatPawAI 暂未提供图像生成/编辑接口，请切换到文本试验或选择其他服务。",
    modelIdPrefixes: [],
    textModelPrefixes: [],
    imageModelKeywords: [],
    imageCapabilities: [],
    textCapabilities: ["chat"],
  },
};
