import type { AccountProviderDefinition } from "./types";

export const codebuddyProvider: AccountProviderDefinition = {
  id: "codebuddy",
  label: "CodeBuddy",
  filterLabel: "CodeBuddy",
  exportFilename: "webchat2api_codebuddy.txt",
  exportButtonLabel: "导出 CodeBuddy TXT",
  selectedExportButtonLabel: "导出所选 CodeBuddy TXT",
  canExportWithoutTokens: false,
  importTokenCopy: {
    label: "CodeBuddy key",
    placeholder: "每行一个 CodeBuddy key，例如 ck_...",
    fileHelp: "TXT 每行一个 CodeBuddy key。",
    successLabel: "CodeBuddy key 导入完成",
    submitLabel: "导入 CodeBuddy key",
  },
  importSessionCopy: {
    label: "暂不支持",
    placeholder: "CodeBuddy 当前使用 key 导入。",
    help: "请使用手动 key 导入。",
    successLabel: "CodeBuddy key 导入完成",
    submitLabel: "暂不支持",
    parseJsonAccessToken: false,
  },
  importMethods: ["token"],
  importFlowCopy: {
    providerDescription: "通过 CodeBuddy key 导入账号，使用 tx- 前缀模型。",
    methodIntro: "粘贴 CodeBuddy key 后即可使用 tx- 模型。",
    emptyMethodsLabel: "当前没有可用的 CodeBuddy 导入方式。",
    cpaHelp: "当前 CodeBuddy 不支持本地 JSON 文件导入。",
    remoteCpaDescription: "当前 CodeBuddy 不支持远程 CPA 快捷入口。",
    sub2apiDescription: "当前 CodeBuddy 不支持 Sub2API 快捷入口。",
  },
  metadataLabel: "CodeBuddy 账号",
  accountInfoHelp: "用于 CodeBuddy tx- 前缀聊天模型。",
  tokenHiddenLabel: "CodeBuddy key hidden",
  badgeVariant: "outline",
  quota: {
    applicable: false,
    unavailableLabel: "未知",
    unlimitedTypes: [],
  },
  refresh: {
    enabled: false,
    rowTitle: "CodeBuddy key 当前不支持刷新",
  },
  trial: {
    enabled: true,
    textFallbackModels: [
      "tx-auto",
      "tx-deepseek-v3",
      "tx-deepseek-v3-0324",
      "tx-deepseek-r1",
      "tx-glm-5.1",
      "tx-glm-5.2",
      "tx-glm-4.6",
      "tx-minimax-m3",
      "tx-kimi-k2.6",
    ],
    textFallbackMode: "always",
    imageFallbackModels: [],
    imageUnsupportedCopy: "CodeBuddy 暂未提供图像生成/编辑接口，请切换到文本试验或选择其他服务。",
    imageNoMetadataCopy: "CodeBuddy 暂未提供图像生成/编辑接口，请切换到文本试验或选择其他服务。",
    modelIdPrefixes: ["tx-"],
    textModelPrefixes: [],
    imageModelKeywords: [],
    imageCapabilities: [],
    textCapabilities: ["chat"],
  },
};
