import type { AccountProviderDefinition } from "./types";

export const geminiProvider: AccountProviderDefinition = {
  id: "gemini",
  label: "Gemini",
  filterLabel: "Gemini",
  exportFilename: "webchat2api_gemini.txt",
  exportButtonLabel: "导出 Gemini TXT",
  selectedExportButtonLabel: "导出所选 Gemini TXT",
  canExportWithoutTokens: true,
  importTokenCopy: {
    label: "Gemini Cookie 列表",
    placeholder: "每行一组完整 Gemini Cookie/session，例如 __Secure-1PSID=...; __Secure-1PSIDTS=...；也可粘贴后端支持的 Gemini session 行。",
    fileHelp: "支持 `.txt`，每行一组完整 Gemini Cookie/session；需至少包含 __Secure-1PSID，__Secure-1PSIDTS 可一并包含。",
    successLabel: "Gemini Cookie 导入完成",
    submitLabel: "导入 Gemini Cookie",
  },
  importSessionCopy: {
    label: "Gemini Cookie 双字段",
    placeholder: "可粘贴完整 Cookie 行，或分别填写 __Secure-1PSID / __Secure-1PSIDTS",
    help: "推荐使用上方 Gemini Cookie 列表导入完整 cookie/session 行；如只拿到单个 cookie 值，也可以在这里分别填写 __Secure-1PSID 和可选的 __Secure-1PSIDTS，提交时会交给后端归一化。",
    successLabel: "Gemini Cookie 导入完成",
    submitLabel: "导入 Gemini Cookie",
    parseJsonAccessToken: false,
  },
  importMethods: ["token", "session", "cpa"],
  importFlowCopy: {
    providerDescription: "导入 Gemini 完整 Cookie/session 行，或使用双字段方式补充单个 cookie 值。",
    methodIntro: "Gemini 推荐直接粘贴/上传完整 Cookie 列表；双字段方式仍可用于只拿到 __Secure-1PSID 与 __Secure-1PSIDTS 值的场景，后端会归一化为账号池凭据。",
    emptyMethodsLabel: "当前没有可用的 Gemini 导入方式。",
    cpaHelp: "JSON 文件应包含 Gemini cookie/session 字段或 access_token/accessToken 形式的归一化凭据；导入时会强制归入 Gemini 分组。",
    remoteCpaDescription: "当前 Gemini 不提供远程 CPA 快捷入口。",
    sub2apiDescription: "当前 Gemini 不提供 Sub2API 快捷入口。",
  },
  metadataLabel: "Gemini Cookie / Session",
  accountInfoHelp: "用于 Gemini cookie/session 账号池，不用于 GPT 图像额度刷新。",
  tokenHiddenLabel: "Gemini session hidden",
  badgeVariant: "outline",
  quota: {
    applicable: false,
    unavailableLabel: "不适用",
    unlimitedTypes: [],
  },
  refresh: {
    enabled: false,
    rowTitle: "Gemini 账号当前不支持账号刷新",
  },
  trial: {
    enabled: true,
    textFallbackModels: [],
    textFallbackMode: "always",
    imageFallbackModels: [],
    imageUnsupportedCopy: "Gemini 暂未提供图像生成/编辑接口，请切换到文本试验或选择其他服务。",
    imageNoMetadataCopy: "Gemini 暂未提供图像生成/编辑接口，请切换到文本试验或选择其他服务。",
    modelIdPrefixes: ["gemini-"],
    textModelPrefixes: ["gemini-"],
    imageModelKeywords: [],
    imageCapabilities: ["image", "image_edit"],
    textCapabilities: ["chat"],
  },
};
