import type { AccountProviderDefinition } from "./types";

export const geminiProvider: AccountProviderDefinition = {
  id: "gemini",
  label: "Gemini",
  filterLabel: "Gemini",
  exportFilename: "webchat2api_gemini.txt",
  exportButtonLabel: "导出 Gemini TXT",
  selectedExportButtonLabel: "导出所选 Gemini TXT",
  canExportWithoutTokens: true,
  importTokenCopy: {
    label: "Gemini Cookie 列表",
    placeholder: "每行一组 Gemini cookie/session，需包含 __Secure-1PSID，可包含 __Secure-1PSIDTS...",
    fileHelp: "支持 `.txt`，每行一组 Gemini cookie/session；需包含 __Secure-1PSID，可包含 __Secure-1PSIDTS。",
    successLabel: "Gemini Cookie 导入完成",
    submitLabel: "导入 Gemini Cookie",
  },
  importSessionCopy: {
    label: "Gemini cookie / session",
    placeholder: "每行一组 Gemini cookie/session，需包含 __Secure-1PSID，可包含 __Secure-1PSIDTS...",
    help: "Gemini 请粘贴每行一组 cookie/session，需包含 `__Secure-1PSID`，可包含 `__Secure-1PSIDTS`。GPT 的 Session JSON 不是 Gemini 的正确来源。",
    successLabel: "Gemini Cookie 导入完成",
    submitLabel: "导入 Gemini Cookie",
    parseJsonAccessToken: false,
  },
  importMethods: ["session", "cpa"],
  importFlowCopy: {
    providerDescription: "导入 Gemini cookie/session JSON；不是普通 Bearer token。",
    methodIntro: "Gemini 需要 cookie/session 凭据，至少包含 __Secure-1PSID；后端会将可用字段归一化为账号池凭据。",
    emptyMethodsLabel: "当前没有可用的 Gemini 导入方式。",
    cpaHelp: "JSON 文件应包含 Gemini cookie/session 字段或 access_token/accessToken 形式的归一化凭据；导入时会强制归入 Gemini 分组。",
    remoteCpaDescription: "当前 Gemini 不提供远程 CPA 快捷入口。",
    sub2apiDescription: "当前 Gemini 不提供 Sub2API 快捷入口。",
  },
  metadataLabel: "Gemini Cookie / Session",
  accountInfoHelp: "用于 Gemini cookie/session 账号池，不用于 GPT 图像额度刷新。",
  tokenHiddenLabel: "Gemini session hidden",
  badgeVariant: "outline",
  quota: {
    applicable: false,
    unavailableLabel: "不适用",
    unlimitedTypes: [],
  },
  refresh: {
    enabled: false,
    rowTitle: "Gemini 账号当前不支持账号刷新",
  },
  trial: {
    enabled: true,
    textFallbackModels: [],
    textFallbackMode: "always",
    imageFallbackModels: [],
    imageUnsupportedCopy: "Gemini 暂未提供图像生成/编辑接口，请切换到文本试验或选择其他服务。",
    imageNoMetadataCopy: "Gemini 暂未提供图像生成/编辑接口，请切换到文本试验或选择其他服务。",
    modelIdPrefixes: ["gemini-"],
    textModelPrefixes: ["gemini-"],
    imageModelKeywords: [],
    imageCapabilities: ["image", "image_edit"],
    textCapabilities: ["chat"],
  },
};
