import type { AccountProviderDefinition } from "./types";

export const geminiProvider: AccountProviderDefinition = {
  id: "gemini",
  label: "Gemini",
  filterLabel: "Gemini",
  exportFilename: "webchat2api_gemini.txt",
  exportButtonLabel: "导出 Gemini TXT",
  selectedExportButtonLabel: "导出所选 Gemini TXT",
  canExportWithoutTokens: true,
  importTokenCopy: {
    label: "暂不支持",
    placeholder: "Gemini 目前只支持 Cookie 双字段导入。",
    fileHelp: "Gemini 目前不支持 TXT、完整 Cookie 或其他账号导入方式。",
    successLabel: "Gemini Cookie 导入完成",
    submitLabel: "暂不支持",
  },
  importSessionCopy: {
    label: "Gemini Cookie 双字段",
    placeholder: "分别填写两个 cookie 的等号右侧完整值，不要包含 cookie 名称。",
    help: "目前只支持双字段导入：__Secure-1PSID 和 __Secure-1PSIDTS。请只填写等号右侧的完整值，不要粘贴 cookie 名称、等号或分号。",
    successLabel: "Gemini Cookie 导入完成",
    submitLabel: "导入 Gemini Cookie",
    parseJsonAccessToken: false,
  },
  importMethods: ["session"],
  importFlowCopy: {
    providerDescription: "使用 __Secure-1PSID 与 __Secure-1PSIDTS 双字段导入 Gemini Cookie。",
    methodIntro: "Gemini 目前只支持 Cookie 双字段导入：分别粘贴 __Secure-1PSID 和 __Secure-1PSIDTS 的等号右侧完整值。",
    emptyMethodsLabel: "当前没有可用的 Gemini 导入方式。",
    cpaHelp: "当前 Gemini 不支持本地 JSON 文件导入。",
    remoteCpaDescription: "当前 Gemini 不支持远程 CPA 快捷入口。",
    sub2apiDescription: "当前 Gemini 不支持 Sub2API 快捷入口。",
  },
  metadataLabel: "Gemini Cookie / Session",
  accountInfoHelp: "用于 Gemini cookie/session 账号池，不用于 GPT 图像额度刷新。",
  tokenHiddenLabel: "Gemini session hidden",
  badgeVariant: "outline",
  quota: {
    applicable: false,
    unavailableLabel: "不适用",
    unlimitedTypes: [],
  },
  refresh: {
    enabled: true,
    buttonLabel: "刷新 Gemini Cookie 会话",
    selectedButtonLabel: "刷新选中 Gemini Cookie 会话",
    rowTitle: "通过后端轮换/更新 session cookies 刷新 Gemini 账号",
  },
  trial: {
    enabled: true,
    textFallbackModels: [],
    textFallbackMode: "always",
    imageFallbackModels: [],
    imageUnsupportedCopy: "Gemini 暂未提供图像生成/编辑接口，请切换到文本试验或选择其他服务。",
    imageNoMetadataCopy: "Gemini 暂未提供图像生成/编辑接口，请切换到文本试验或选择其他服务。",
    modelIdPrefixes: ["gemini-"],
    textModelPrefixes: ["gemini-"],
    imageModelKeywords: [],
    imageCapabilities: ["image", "image_edit"],
    textCapabilities: ["chat"],
  },
};
