import type { AccountProviderDefinition } from "./types";

export const gptProvider: AccountProviderDefinition = {
  id: "gpt",
  label: "GPT",
  filterLabel: "GPT",
  exportFilename: "webchat2api-gpt.txt",
  exportButtonLabel: "导出 GPT TXT",
  selectedExportButtonLabel: "导出所选 GPT TXT",
  canExportWithoutTokens: false,
  importTokenCopy: {
    label: "Access Token 列表",
    placeholder: "每行一个 Access Token...",
    fileHelp: "支持 `.txt`，文件内容也是一行一个 Token。",
    successLabel: "Access Token 导入完成",
    submitLabel: "导入 Token",
  },
  importSessionCopy: {
    label: "Session JSON",
    placeholder: '粘贴完整 JSON，例如包含 "accessToken" 的对象...',
    help: "",
    successLabel: "GPT Session JSON 导入完成",
    submitLabel: "导入 JSON",
    emptyMessage: "请先粘贴完整 GPT Session JSON",
    parseErrorMessage: "GPT Session JSON 解析失败",
    parseJsonAccessToken: true,
    sessionUrl: "https://chatgpt.com/api/auth/session",
  },
  importMethods: ["token", "session", "cpa", "remote-cpa", "sub2api"],
  importFlowCopy: {
    providerDescription: "导入 GPT access token、ChatGPT session JSON，或 CPA/OpenAI 账号 JSON。",
    methodIntro: "GPT 支持 token 文本、Session JSON 和 CPA/OpenAI JSON；导入后会刷新邮箱、套餐与图像额度。",
    emptyMethodsLabel: "当前没有可用的 GPT 导入方式。",
    cpaHelp: "每个 JSON 文件应包含 access_token 或 accessToken；缺省会按 GPT 导入，codex 类型会保留为导出类型。",
    remoteCpaDescription: "前往设置页配置远程 CPA 服务器后导入 OpenAI/GPT 账号。",
    sub2apiDescription: "前往设置页配置 Sub2API 服务器，再选择其中的 OpenAI/GPT 账号。",
  },
  metadataLabel: "GPT 套餐",
  accountInfoHelp: "用于 GPT 账号元数据与图像额度。",
  tokenHiddenLabel: "凭据已隐藏",
  badgeVariant: "outline",
  quota: {
    applicable: true,
    metricLabel: "GPT 图像额度",
    unavailableLabel: "不适用",
    unlimitedTypes: ["pro", "prolite"],
    unknownField: "image_quota_unknown",
  },
  refresh: {
    enabled: true,
    buttonLabel: "刷新 GPT 账号信息和额度",
    selectedButtonLabel: "刷新选中 GPT 账号信息和额度",
    rowTitle: "刷新 GPT 账号信息和额度",
  },
  trial: {
    enabled: true,
    textFallbackModels: ["gpt-4.1-mini", "gpt-4o-mini", "gpt-3.5-turbo"],
    textFallbackMode: "always",
    imageFallbackModels: ["gpt-image-2", "codex-gpt-image-2"],
    imageUnsupportedCopy: "当前 GPT 模型列表未返回图像能力。",
    modelIdPrefixes: ["gpt-", "codex-", "dall-e"],
    textModelPrefixes: ["gpt-"],
    imageModelKeywords: ["image", "dall-e", "gpt-image", "codex-gpt-image"],
    imageCapabilities: ["image", "image_edit"],
    textCapabilities: ["chat"],
  },
};
