import type { AccountProviderDefinition } from "./types";

export const grokProvider: AccountProviderDefinition = {
  id: "grok",
  label: "Grok",
  filterLabel: "Grok",
  exportFilename: "webchat2api_grok.txt",
  exportButtonLabel: "导出 Grok TXT",
  selectedExportButtonLabel: "导出所选 Grok TXT",
  canExportWithoutTokens: false,
  importTokenCopy: {
    label: "Grok SSO Cookie 列表",
    placeholder: "每行一个 Grok SSO：填写裸 SSO 值，或单个 sso=完整值...",
    fileHelp: "支持 `.txt`，每行一个 Grok SSO：裸 SSO 值，或单个 `sso=完整值`；不支持 sso-rw、完整 Cookie header、JSON/CPA 或其他账号导入方式。",
    successLabel: "Grok SSO 导入完成",
    submitLabel: "导入 Grok SSO",
  },
  importSessionCopy: {
    label: "Grok SSO Cookie 列表",
    placeholder: "每行一个 Grok SSO：填写裸 SSO 值，或单个 sso=完整值...",
    help: "Grok 目前只支持 SSO Cookie 列表导入：每行填写裸 SSO 值，或单个 `sso=完整值`。不支持 sso-rw、完整 Cookie header、JSON/CPA 或其他账号导入方式。",
    successLabel: "Grok SSO 导入完成",
    submitLabel: "导入 Grok SSO",
    parseJsonAccessToken: false,
  },
  importMethods: ["token"],
  importFlowCopy: {
    providerDescription: "导入 Grok SSO Cookie 列表，每行一个裸 SSO 值或单个 `sso=完整值`。",
    methodIntro: "Grok 目前只支持 SSO Cookie 列表导入；不支持 sso-rw、完整 Cookie header、JSON/CPA 或其他账号导入方式。",
    emptyMethodsLabel: "当前没有可用的 Grok 导入方式。",
    cpaHelp: "当前 Grok 不支持本地 JSON 文件导入。",
    remoteCpaDescription: "当前 Grok 不支持远程 CPA 快捷入口。",
    sub2apiDescription: "当前 Grok 不支持 Sub2API 快捷入口。",
  },
  metadataLabel: "Grok 文本模型计划/池",
  accountInfoHelp: "用于 Grok 文本模型，不用于 ChatGPT 图像生成。",
  tokenHiddenLabel: "凭据已隐藏",
  badgeVariant: "info",
  quota: {
    applicable: false,
    unavailableLabel: "不适用",
    unlimitedTypes: [],
  },
  refresh: {
    enabled: true,
    buttonLabel: "刷新 Grok 账号信息",
    selectedButtonLabel: "刷新选中 Grok 账号信息",
    rowTitle: "刷新 Grok 账号信息",
  },
  trial: {
    enabled: true,
    textFallbackModels: ["grok-4.3"],
    textFallbackMode: "without-metadata",
    imageFallbackModels: [],
    imageUnsupportedCopy: "当前 Grok 模型列表未返回图像能力。",
    imageNoMetadataCopy: "当前无法确认 Grok 图像能力，已禁用服务选择。",
    modelIdPrefixes: ["grok-"],
    textModelPrefixes: ["grok-"],
    imageModelKeywords: [],
    imageCapabilities: ["image", "image_edit"],
    textCapabilities: ["chat"],
  },
};
