import type { AccountProviderDefinition } from "./types";

export const grokProvider: AccountProviderDefinition = {
  id: "grok",
  label: "Grok",
  filterLabel: "Grok",
  exportFilename: "webchat2api_grok.txt",
  exportButtonLabel: "导出 Grok TXT",
  selectedExportButtonLabel: "导出所选 Grok TXT",
  canExportWithoutTokens: false,
  importTokenCopy: {
    label: "Grok SSO Cookie 列表",
    placeholder: "每行一个 Grok sso Cookie，例如 sso=xxxx；不支持纯 token 或 sso-rw...",
    fileHelp: "支持 `.txt`，每行必须包含 Grok `sso=` Cookie；不支持纯 token、sso-rw 或 ChatGPT Session JSON。",
    successLabel: "Grok SSO 导入完成",
    submitLabel: "导入 Grok SSO",
  },
  importSessionCopy: {
    label: "Grok sso Cookie",
    placeholder: "每行一个 Grok sso Cookie，例如 sso=xxxx...",
    help: "Grok 账号导入只支持 `sso=` Cookie；不支持纯 token、sso-rw 或 GPT Session JSON。",
    successLabel: "Grok SSO 导入完成",
    submitLabel: "导入 Grok SSO",
    parseJsonAccessToken: false,
  },
  importMethods: ["token", "cpa", "remote-cpa", "sub2api"],
  importFlowCopy: {
    providerDescription: "导入 Grok `sso=` Cookie 或包含 sso 字段的账号 JSON。",
    methodIntro: "Grok 账号池只接受 `sso=` Cookie；请不要粘贴纯 token、sso-rw 或 ChatGPT Session JSON。",
    emptyMethodsLabel: "当前没有可用的 Grok 导入方式。",
    cpaHelp: "JSON 文件应包含 Grok sso 字段，或 access_token/accessToken 中包含 `sso=` Cookie；导入时会强制归入 Grok 分组。",
    remoteCpaDescription: "前往设置页配置远程 CPA 服务器后导入 Grok 账号。",
    sub2apiDescription: "前往设置页配置 Sub2API 服务器，再选择其中的 Grok 账号。",
  },
  metadataLabel: "Grok 文本模型计划/池",
  accountInfoHelp: "用于 Grok 文本模型，不用于 ChatGPT 图像生成。",
  tokenHiddenLabel: "凭据已隐藏",
  badgeVariant: "info",
  quota: {
    applicable: false,
    unavailableLabel: "不适用",
    unlimitedTypes: [],
  },
  refresh: {
    enabled: false,
    rowTitle: "Grok 账号当前不支持账号刷新",
  },
  trial: {
    enabled: true,
    textFallbackModels: ["grok-4.3"],
    textFallbackMode: "without-metadata",
    imageFallbackModels: [],
    imageUnsupportedCopy: "当前 Grok 模型列表未返回图像能力。",
    imageNoMetadataCopy: "当前无法确认 Grok 图像能力，已禁用服务选择。",
    modelIdPrefixes: ["grok-"],
    textModelPrefixes: ["grok-"],
    imageModelKeywords: [],
    imageCapabilities: ["image", "image_edit"],
    textCapabilities: ["chat"],
  },
};
