import type { AccountProviderDefinition } from "./types";

export const joycodeProvider: AccountProviderDefinition = {
  id: "joycode",
  label: "JoyCode",
  filterLabel: "JoyCode",
  exportFilename: "webchat2api_joycode.txt",
  exportButtonLabel: "导出 JoyCode TXT",
  selectedExportButtonLabel: "导出所选 JoyCode TXT",
  canExportWithoutTokens: false,
  importTokenCopy: {
    label: "JoyCode pt_key + user_id",
    placeholder: "每行一个 pt_key，推荐使用 OAuth 回调 URL 导入以自动校验 user_id。",
    fileHelp: "TXT 每行一个 pt_key。",
    successLabel: "JoyCode 凭据导入完成",
    submitLabel: "导入 JoyCode 凭据",
  },
  importSessionCopy: {
    label: "OAuth 回调 URL 或 pt_key",
    placeholder: "粘贴 http://127.0.0.1:34891/?pt_key=... 或纯 pt_key",
    help: "先点击浏览器登录获取授权 URL，完成后把回调 URL 或 pt_key 粘贴到这里。",
    successLabel: "JoyCode OAuth 导入完成",
    submitLabel: "提交 JoyCode OAuth",
    parseJsonAccessToken: false,
  },
  importMethods: ["session", "browser-login", "token"],
  importFlowCopy: {
    providerDescription: "通过 JoyCode OAuth、本机 JoyCode state 或手动 pt_key 导入账号。",
    methodIntro: "推荐使用 OAuth 回调 URL 导入；本机安装 JoyCode IDE 时也可使用后端自动导入接口。",
    emptyMethodsLabel: "当前没有可用的 JoyCode 导入方式。",
    cpaHelp: "当前 JoyCode 不支持本地 JSON 文件导入。",
    remoteCpaDescription: "当前 JoyCode 不支持远程 CPA 快捷入口。",
    sub2apiDescription: "当前 JoyCode 不支持 Sub2API 快捷入口。",
  },
  metadataLabel: "JoyCode 账号",
  accountInfoHelp: "用于 JoyCode 模型、web-search、rerank 和 Claude 原生通道。",
  tokenHiddenLabel: "JoyCode pt_key hidden",
  badgeVariant: "outline",
  quota: {
    applicable: false,
    unavailableLabel: "未知",
    unlimitedTypes: [],
  },
  refresh: {
    enabled: true,
    buttonLabel: "刷新 JoyCode 凭据",
    selectedButtonLabel: "刷新选中 JoyCode 凭据",
    rowTitle: "通过 JoyCode userInfo 校验并刷新 pt_key",
  },
  trial: {
    enabled: true,
    textFallbackModels: ["JoyAI-Code", "GLM-5.1", "Kimi-K2.6", "MiniMax-M2.7"],
    textFallbackMode: "always",
    imageFallbackModels: [],
    imageUnsupportedCopy: "JoyCode 暂未提供图像生成/编辑接口，请切换到文本试验或选择其他服务。",
    imageNoMetadataCopy: "JoyCode 暂未提供图像生成/编辑接口，请切换到文本试验或选择其他服务。",
    modelIdPrefixes: [],
    textModelPrefixes: [],
    imageModelKeywords: [],
    imageCapabilities: [],
    textCapabilities: ["chat"],
  },
};
