import type { AccountProviderDefinition } from "./types";

export const qoderProvider: AccountProviderDefinition = {
  id: "qoder",
  label: "Qoder",
  filterLabel: "Qoder",
  exportFilename: "webchat2api_qoder.txt",
  exportButtonLabel: "导出 Qoder TXT",
  selectedExportButtonLabel: "导出所选 Qoder TXT",
  canExportWithoutTokens: false,
  importTokenCopy: {
    label: "Qoder device token",
    placeholder: "每行一个 JSON：{\"device_token\":\"dt-...\",\"user_id\":\"...\",\"machine_id\":\"...\"}",
    fileHelp: "TXT 每行一个 Qoder device token JSON，或 device_token,user_id,machine_id。",
    successLabel: "Qoder 凭据导入完成",
    submitLabel: "导入 Qoder 凭据",
  },
  importSessionCopy: {
    label: "Qoder device token",
    placeholder: "Qoder 推荐使用浏览器授权登录；也可粘贴 device token JSON。",
    help: "浏览器授权会自动生成 machine_id 并轮询 Qoder device token。",
    successLabel: "Qoder 凭据导入完成",
    submitLabel: "导入 Qoder 凭据",
    parseJsonAccessToken: false,
  },
  importMethods: ["browser-login", "token"],
  importFlowCopy: {
    providerDescription: "通过 Qoder device flow 授权登录，自动保存 device token、user_id 和 machine_id。",
    methodIntro: "推荐使用浏览器授权；也可以手动导入 Qoder device token JSON。",
    emptyMethodsLabel: "当前没有可用的 Qoder 导入方式。",
    cpaHelp: "当前 Qoder 不支持本地 JSON 文件导入。",
    remoteCpaDescription: "当前 Qoder 不支持远程 CPA 快捷入口。",
    sub2apiDescription: "当前 Qoder 不支持 Sub2API 快捷入口。",
  },
  metadataLabel: "Qoder 账号",
  accountInfoHelp: "用于 Qoder al- 前缀聊天模型。",
  tokenHiddenLabel: "Qoder token hidden",
  badgeVariant: "outline",
  quota: {
    applicable: false,
    unavailableLabel: "未知",
    unlimitedTypes: [],
  },
  refresh: {
    enabled: false,
    rowTitle: "Qoder device token 当前不支持刷新，过期后重新授权登录",
  },
  trial: {
    enabled: true,
    textFallbackModels: [
      "al-qwen3.7-max",
      "al-qwen3.7-plus",
      "al-glm-5.2",
      "al-kimi-k2.6",
      "al-minimax-m2.7",
    ],
    textFallbackMode: "always",
    imageFallbackModels: [],
    imageUnsupportedCopy: "Qoder 暂未提供图像生成/编辑接口，请切换到文本试验或选择其他服务。",
    imageNoMetadataCopy: "Qoder 暂未提供图像生成/编辑接口，请切换到文本试验或选择其他服务。",
    modelIdPrefixes: ["al-"],
    textModelPrefixes: [],
    imageModelKeywords: [],
    imageCapabilities: [],
    textCapabilities: ["chat"],
  },
};
