import type { AccountProviderDefinition } from "./types";

export const qoderProvider: AccountProviderDefinition = {
  id: "qoder",
  label: "Qoder",
  filterLabel: "Qoder",
  exportFilename: "webchat2api_qoder.txt",
  exportButtonLabel: "导出 Qoder TXT",
  selectedExportButtonLabel: "导出所选 Qoder TXT",
  canExportWithoutTokens: false,
  importTokenCopy: {
    label: "Qoder PAT",
    placeholder: "每行一个 Qoder PAT，例如 pt-...",
    fileHelp: "TXT 每行一个 Qoder PAT。",
    successLabel: "Qoder PAT 导入完成",
    submitLabel: "导入 Qoder PAT",
  },
  importSessionCopy: {
    label: "暂不支持",
    placeholder: "Qoder 当前只支持 PAT 导入。",
    help: "请使用手动 PAT 导入。",
    successLabel: "Qoder PAT 导入完成",
    submitLabel: "暂不支持",
    parseJsonAccessToken: false,
  },
  importMethods: ["token"],
  importFlowCopy: {
    providerDescription: "通过 Qoder PAT 导入账号，使用 al- 前缀模型。",
    methodIntro: "粘贴 Qoder PAT 后即可使用 al- 模型。",
    emptyMethodsLabel: "当前没有可用的 Qoder 导入方式。",
    cpaHelp: "当前 Qoder 不支持本地 JSON 文件导入。",
    remoteCpaDescription: "当前 Qoder 不支持远程 CPA 快捷入口。",
    sub2apiDescription: "当前 Qoder 不支持 Sub2API 快捷入口。",
  },
  metadataLabel: "Qoder 账号",
  accountInfoHelp: "用于 Qoder al- 前缀聊天模型。",
  tokenHiddenLabel: "Qoder PAT hidden",
  badgeVariant: "outline",
  quota: {
    applicable: false,
    unavailableLabel: "未知",
    unlimitedTypes: [],
  },
  refresh: {
    enabled: false,
    rowTitle: "Qoder PAT 当前不支持刷新",
  },
  trial: {
    enabled: true,
    textFallbackModels: [
      "al-qwen3.7-max",
      "al-qwen3.7-plus",
      "al-glm-5.2",
      "al-kimi-k2.6",
      "al-minimax-m2.7",
    ],
    textFallbackMode: "always",
    imageFallbackModels: [],
    imageUnsupportedCopy: "Qoder 暂未提供图像生成/编辑接口，请切换到文本试验或选择其他服务。",
    imageNoMetadataCopy: "Qoder 暂未提供图像生成/编辑接口，请切换到文本试验或选择其他服务。",
    modelIdPrefixes: ["al-"],
    textModelPrefixes: [],
    imageModelKeywords: [],
    imageCapabilities: [],
    textCapabilities: ["chat"],
  },
};
